/*DROP TABLE PERSONS;

CREATE TABLE PERSONS (
ID INTEGER PRIMARY KEY,
  FIO VARCHAR(255),
  DOB VARCHAR(255),
  PHONE VARCHAR(255),
  EMAIL VARCHAR(255),
  SKYPE VARCHAR(255),
  AVATAR VARCHAR(255),
  TARGET INTEGER,
  EXPERIENCES VARCHAR(255),
  EDUCATIONS VARCHAR(255),
  ADDITIONAL_EDUCATIONS VARCHAR(255),
  SKILLS VARCHAR(255)

);*/

--INSERT INTO EMPLOYEE(I_ID, S_Login, S_Name, I_Age,S_Role) VALUES(4,'Andry','Andrey',28,'admin');
--INSERT INTO EMPLOYEE(I_ID, S_Login, S_Name, I_Age,S_Role) VALUES(5,'Petr','Petya',29,'web disainer');
--INSERT INTO EMPLOYEE(I_ID, S_Login, S_Name, I_Age,S_Role) VALUES(6,'Serzh','Sergey',58,'Driver');
--INSERT INTO EMPLOYEE(I_ID, S_Login, S_Name, I_Age,S_Role) VALUES(7,'Boss','BossBoss',32,'boss');